apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: myapp
    pod: pod-1
spec:
  containers:
    - name: container-1
      image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    app: myapp
    pod: pod-2
spec:
  containers:
    - name: container-2
      image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    app: myapp
    pod: pod-3
spec:
  containers:
    - name: container-3
      image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-4
  labels:
    app: myapp
    pod: pod-4
spec:
  containers:
    - name: container-4
      image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-5
  labels:
    app: myapp
    pod: pod-5
spec:
  containers:
    - name: container-5
      image: nginx:latest
